### ISSUE TITLE
Focus outline is not really visible

### ISSUE THREAD

**Issue by myrdn** [clic2000/clic2000.fr#14]
As we have blue borders on our buttons it's hard to see if the element has the focus with the default styles on firefox.

![The contact button with focus](https://user-images.githubusercontent.com/43375226/136216332-b1ad75ae-8ec8-4278-86a7-48ca3ba5d2b4.png)

We should add different styles to make it more readable.

**Comment by mthld** [comment]
Fixed by #15.
