### ISSUE TITLE
Different buttons on mobile?

### ISSUE THREAD

**Issue by mthld** [clic2000/clic2000.fr#3]
Margot suggested that we have the same buttons as the "contact" one on mobile views. Do we want that? Especially if #2 is fixed?

<img width="342" alt="Screenshot 2021-06-28 at 15 07 01" src="https://user-images.githubusercontent.com/41020854/123641539-a4c82580-d822-11eb-807b-f84ea32f5ba9.png">

**Comment by myrdn** [comment]
Don't know if we should make the references button like the contact one or the contact one like the references one ? I like Milo idea with this big padding.

What do you think ?

**Comment by myrdn** [comment]
I made the contact button like the ones of the menu, check the preprod and let me know what do you think.

**Comment by mthld** [comment]
I like it very much this way. Closing, thanks!
