### ISSUE TITLE
Non-homogenous font size

### ISSUE THREAD

**Issue by mthld** [clic2000/clic2000.fr#4]
As of today we have two different font sizes on the website.

The smaller one on index and references pages:
<img width="320" alt="Screenshot 2021-07-08 at 09 50 39" src="https://user-images.githubusercontent.com/41020854/124884216-5d842680-dfd2-11eb-9b55-504a7b5d7a95.png"><img width="321" alt="Screenshot 2021-07-08 at 09 50 54" src="https://user-images.githubusercontent.com/41020854/124884227-5f4dea00-dfd2-11eb-8fc8-c72e313b94d8.png">

The bigger one on contact and legal pages:
<img width="321" alt="Screenshot 2021-07-08 at 09 51 16" src="https://user-images.githubusercontent.com/41020854/124884320-74c31400-dfd2-11eb-8835-a69f300402ff.png"><img width="318" alt="Screenshot 2021-07-08 at 09 51 27" src="https://user-images.githubusercontent.com/41020854/124884330-75f44100-dfd2-11eb-820f-fe2a79a0af31.png">

I kinda like the fact that the font is bigger on mobile devices, it's easier to read on my 2020 iPhone SE, but I understand that it makes it more difficult to arrange content.

I do think we should do something about it tho.

**Comment by myrdn** [comment]
Ok so I removed the bigger font-size on contact and legals pages. Making the font bigger on the home page and references one breaks everything. 24003dc

**Comment by mthld** [comment]
> Ok so I removed the bigger font-size on contact and legals pages. Making the font bigger on the home page and references one breaks everything. [24003dc](https://github.com/clic2000/clic2000.fr/commit/24003dcc2f86f050a3171de5a147ded0ee661916)

Thanks! Looks good on mobile, but now it seems broken on desktop.

See the differences between the index and legal pages for example:
<img width="1438" alt="Screenshot 2021-07-09 at 10 14 48" src="https://user-images.githubusercontent.com/41020854/125046809-a6a1ac80-e09e-11eb-958c-49dea1a8abb3.png">

<img width="1438" alt="Screenshot 2021-07-09 at 10 14 40" src="https://user-images.githubusercontent.com/41020854/125046847-aef9e780-e09e-11eb-80de-56d50d9c5532.png">

It's the same with the contact page and references, it looks like there is a gap between index/references & contact/legals.

**Comment by myrdn** [comment]
Now contact and legals have the same font size of index. But I think it's too big...

Also having this font size on references breaks the columns layout.

Don't really know what to do about it, I sugest that we try to have references font size on contact and legals and keep the font-size of the mockup on the index, but it mean that we won't have the same font-size everywhere...

**Comment by myrdn** [comment]
You can't see it's broken because I didn't change the font size on the references page. The gap between this page and the others isn't very important, shall we close this issue ?

**Comment by mthld** [comment]
The main problem to me was the huge gab between pages on mobile view. That's fixed now, thanks! We can close. :)

**Comment by myrdn** [comment]
Take a look at this issue, don't remember why we reopened it @mthld ? Font size seems homogenous on web and mobile, can you confirm on your side ?

**Comment by mthld** [comment]
> Take a look at this issue, don't remember why we reopened it @mthld ? Font size seems homogenous on web and mobile, can you confirm on your side ?

That's true, I don't recall what the problem was. I did a tour of the website from my iPhone and my MacBook & everything seems alright regarding font size now.

Closing!
